//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnifferMC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpAdapters
    {
        public int Id { get; set; }
        public string PortIn { get; set; }
        public string PortOut { get; set; }
        public string Protocol { get; set; }
        public string UiSourceIPAddress { get; set; }
        public string UiDestinationIPAddress { get; set; }
        public string MessageLength { get; set; }
    }
}
